# Generated by Django 4.2.5 on 2023-11-02 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shoppers", "0003_products_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
